[build]
publish = "public"
command = "npm run build && npm run ipfs-deploy"

[context.production.environment]
HUGO_VERSION = "0.62.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://practical-lichterman-5dcc24.netlify.com/*"
  to = "https://360tai.cn/:splat"
  force = true
